config/routes.rb
Ladder::Application.routes.draw do
  resources :teams

  resources :matches

  resources :players

  post 'players/toggle_status/:id' => 'players#toggle_status', as: "toggle_status_player"
  get '/ladder(/:ladder)' => 'ladder#index'
  get '/ladder/index(/:ladder)' => 'ladder#index', as: "ladder_index"

  root :to => 'ladder#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :matches
  has_many :rosters
  has_many :teams, through: :rosters

  # returns fullname
  def fullname
    return "#{first_name} #{last_name}"
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  def index
    @players = Player.order(:first_name).all
  end

  # GET /players/1
  def show
    @player = Player.find(params[:id])
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(player_params[:id])
  end

  # POST /players
  def create
    @player = Player.new(player_params[:player])
    @player.teams << Team.new

    if @player.save
      redirect_to players_path
    else
      render action: "new"
    end
  end

  # PUT /players/1
  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(player_params[:player])
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render action: "edit"
    end
  end

  # POST /players/1
  def toggle_status
    player = Player.find(params[:id])
    player.active = !player.active
    player.save!
    redirect_to players_path
  end


  private

  def player_params
    params.permit :id, player: [:email, :first_name, :last_name, :rank, :active]
  end
end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field', autofocus: true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= render :partial => 'form' %>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_player_path,
              :class => 'btn btn-primary' %>
</div>
<br/>

<table class="table table-striped">

  <tr>
    <th><%= model_class.human_attribute_name("name") %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>

  <tbody>
  <% @players.each do |player| %>
      <tr>
        <td><%= image_tag(gravatar_url(player.email, :size => 32)) %> <%= link_to "#{player.first_name} #{player.last_name}", player_path(player) %></td>

        <td><%= player.created_at.to_formatted_s(:long) %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>

          <% if player.active %>
              <%= link_to "Deactivate",
                          toggle_status_player_path(player),
                          :method => :post,
                          :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm",
                                                                            :default => 'This will remove the ranking for this player.  Are you sure?'))},
                          :class => 'btn btn-mini btn-danger' %>
          <% else %>
              <%= link_to "Activate",
                          toggle_status_player_path(player),
                          :method => :post,
                          :class => 'btn btn-mini btn-primary' %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @player.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @player.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @player.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn' %>
</div>