config/routes.rb
Ladder::Application.routes.draw do
  resources :teams

  resources :matches

  resources :players

  post 'players/toggle_status/:id' => 'players#toggle_status', as: "toggle_status_player"
  get '/ladder(/:ladder)' => 'ladder#index'
  get '/ladder/index(/:ladder)' => 'ladder#index', as: "ladder_index"

  root :to => 'ladder#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :defender, class_name: Team, foreign_key: :defender_id
  belongs_to :challenger, class_name: Team, foreign_key: :challenger_id
  belongs_to :winner, class_name: Team, foreign_key: :winner_id
  validate :challenger_cannot_also_be_the_defender
  validate :player_can_only_be_in_one_team

  delegate :ladder, to: :defender

  def challenger_cannot_also_be_the_defender
    if (challenger_id == defender_id)
      errors.add(:defender_id, ": Challenger can not challenge themselves.")
    end
  end

  def player_can_only_be_in_one_team
    team1 = Team.where(id: challenger_id).includes(:players).limit(2)
    team2 = Team.where(id: defender_id).includes(:players).limit(2)

    return if team1[0].ladder == 1

    same_player = team1[0].players & team2[0].players

    if (same_player.size > 0)
      errors.add(:defender_id, ": A player can only be in one team for a match.")
    end
  end

  # returns matches played
  def self.total_matches(team)
    Match.where("winner_id is not null and (challenger_id = #{team.id} or defender_id = #{team.id})").count
  end

  #returns matches won
  def self.total_wins(team)
    Match.where("winner_id = #{team.id}").count
  end

  #returns matches lost
  def self.total_loses(team)
    Match.where("winner_id is not null and winner_id != #{team.id} and (challenger_id = #{team.id} or defender_id = #{team.id})").count
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  # GET /matches
  def index
    @matches = Match.all.sort_by { |x| x.updated_at}.reverse
  end

  # GET /matches/1
  def show
    @match = Match.find(params[:id])
  end

  # GET /matches/new
  def new
    ladder = params[:ladder].nil? ? 1 : params[:ladder]
    @teams = Team.all_active ladder
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    @participants = [@match.challenger, @match.defender]
  end

  # POST /matches
  def create
    @match = Match.new(new_match_params)

    if @match.save
      Rater::TrueSkillRater.update_ratings @match.winner, @match.defender
      redirect_to ladder_index_path ladder: @match.ladder
    else
      @teams = Team.all_active @match.ladder
      render action: "new"
    end
  end

  # PUT /matches/1
  def update
    @match = Match.find(params[:id])

    if @match.update_attributes(params[:match])
      redirect_to ladder_index_path ladder: @match.ladder
    else
      render action: "edit"
    end
  end

  # DELETE /matches/1
  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to matches_url
  end

  private

  def new_match_params
    new_params = params[:match].merge!({ winner_id: params[:match][:challenger_id] })
    new_params.permit :challenger_id, :defender_id, :winner_id
  end
end

app/views/matches/_form.html.erb
<%= form_for @match, :html => { :class => 'form-horizontal' } do |f| %>

    <% if @match.errors.any? %>
        <div>
          <% @match.errors.full_messages.each do |msg| %>
              <div class="alert alert-error fade in">
                <a href="#" data-dismiss="alert" class="close">×</a>
                <%= msg %>
              </div>
          <% end %>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :challenger_id, 'Winner', :class => 'control-label' %>
      <div class="controls">
        <%= f.select :challenger_id,
          options_from_collection_for_select(@teams, :id, :fullname, @match.challenger_id),
          {}, :class => 'chzn-select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :defender_id, 'Beats Loser', :class => 'control-label' %>
      <div class="controls">
        <%= f.select :defender_id,
          options_from_collection_for_select(@teams, :id, :fullname, @match.defender_id),
          {}, :class => 'chzn-select' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  matches_path, :class => 'btn' %>
    </div>

    <script type="text/javascript">
      $(document).ready(function(){
        $('.chzn-select').chosen();
      });
    </script>
<% end %>

app/views/matches/edit.html.erb
<div class="page-header">
  <h1>And the winner is...</h1>
</div>

<%= form_for @match, :html => { :class => 'form-horizontal' } do |f| %>

    <div class="control-group">
      <%= f.label "Enter Match Winner", :class => 'control-label' %>
      <div class="controls">
        <%= f.select :winner_id, options_from_collection_for_select(@participants, :id, :fullname) %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Update Rankings", class: 'btn btn-primary', data: {confirm: "This will update the ladder rankings.  Are you sure?"} %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  matches_path, :class => 'btn' %>
    </div>

<% end %>

app/views/matches/index.html.erb
<div class="page-header">
  <h1>Zest Ping Pong History</h1>
</div>

<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Defender</th>
    <th>Challenger</th>
    <th>Winner</th>
  </tr>

  <% @matches.each do |match| %>
      <tr>
        <td><%= match.updated_at.to_formatted_s(:long) %></td>
        <td><%= match.defender.fullname unless match.defender.nil? %></td>
        <td><%= match.challenger.fullname unless match.challenger.nil? %></td>
        <td><%= match.winner.fullname unless match.winner.nil? %></td>
        </td>
      </tr>
  <% end %>
</table>

app/views/matches/new.html.erb
<div class="page-header">
  <h1>New Update</h1>
</div>

<%= render 'form' %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Defender:</b>
  <%= @match.defender.last_name %>
</p>

<p>
  <b>Challenger:</b>
  <%= @match.challenger.last_name  %>
</p>

<p>
  <b>Winner:</b>
  <%= @match.winner.last_name unless @match.winner.nil? %>
</p>



<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>