config/routes.rb
Ladder::Application.routes.draw do
  resources :teams

  resources :matches

  resources :players

  post 'players/toggle_status/:id' => 'players#toggle_status', as: "toggle_status_player"
  get '/ladder(/:ladder)' => 'ladder#index'
  get '/ladder/index(/:ladder)' => 'ladder#index', as: "ladder_index"

  root :to => 'ladder#index'

end

app/controllers/ladder_controller.rb
class LadderController < ApplicationController
  def index
    @ladder = params[:ladder]
    @ladder = @ladder.nil? ? 1 : @ladder.to_i
    @ladder = 1 if (@ladder < 1 || @ladder > 2)
    @teams = Team.includes(:rating, :players).
                  where(ladder: @ladder).
                  find_all { |team| team.all_players_active }.
                  sort { |team1, team2| team2.rating.value <=> team1.rating.value }
  end
end

app/views/ladder/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>Ping Pong Ladder</h1>
</div>

<div>
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if @ladder == 1 %>"><a href="<%= ladder_index_path ladder: 1 %>">Singles</a></li>
    <li class="<%= 'active' if @ladder == 2 %>"><a href="<%= ladder_index_path ladder: 2 %>">Doubles</a></li>
  </ul>
</div>

<div>
  <% if @ladder == 1 %>
    <%= link_to 'Enter Match Result', new_match_path, :class => 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Enter Doubles Match Result', new_match_path(ladder: 2), :class => 'btn btn-primary' %>
  <% end %>
</div>

<br/>

<table class="table table-striped">
  <tr>
    <th><%= model_class.human_attribute_name(:rating) %></th>
    <th><%= model_class.human_attribute_name("name") %></th>

    <th><%= model_class.human_attribute_name("Won") %></th>
    <th><%= model_class.human_attribute_name("Lost") %></th>
    <th><%= model_class.human_attribute_name("Matches Played") %></th>
  </tr>
  <tbody>
  <% @teams.each do |team| %>
      <tr>
        <% rank = team.rating.value %>
        <% rank = 'unranked' if rank == nil %>

        <td><%= rank %></td>

        <% if @ladder == 1 %>
          <td> <%= image_tag(gravatar_url(team.players[0].email, :size => 32)) %> <%= team.fullname %></td>
        <% else %>
          <td> <%= image_tag(gravatar_url(team.players[0].email, :size => 32)) %> <%= image_tag(gravatar_url(team.players[1].email, :size => 32)) %> <%= team.fullname %></td>
        <% end %>

        <td><%= Match.total_wins(team) %></td>
        <td><%= Match.total_loses(team) %></td>
        <td><%= Match.total_matches(team) %></td>
      </tr>
  <% end %>
  </tbody>
</table>